### ISSUE TITLE
Party-veranstalter: Price Overview Component including Price-Entry-Tab Component

### ISSUE THREAD

**Issue by tamoit02** [Boersen-Party/Boersenparty-FrontEnd#5]

**Comment by doeiit00** [comment]
Price Overview main done. Missing -> Entery Tab?

**Comment by tamoit02** [comment]
Anstatt den Entry Tab auf dieselbe Seite zu packen, eher einen Knopf für 'Neues Getränk' und dann eine extra Seite mit dem Formular. Außerdem weitere Felder wie Min und Max Preis hinzufügen.
